/* =========================================================
   Keysglade — Datenbasis
   Alle Texte sind eigenständig verfasste Zusammenfassungen
   öffentlich bekannter, allgemeiner Reiseinformationen.
========================================================= */

const CATEGORIES = [
  { id: "beaches", label: "Strände & Natur", icon: "kg-icon-beaches.svg" },
  { id: "cities", label: "Städte & Kultur", icon: "kg-icon-cities.svg" },
  { id: "parks", label: "Freizeitparks", icon: "kg-icon-parks.svg" },
  { id: "food", label: "Essen & Trinken", icon: "kg-icon-food.svg" },
  { id: "wildlife", label: "Tier- & Pflanzenwelt", icon: "kg-icon-wildlife.svg" },
  { id: "history", label: "Geschichte", icon: "kg-icon-history.svg" },
  { id: "art", label: "Kunst & Museen", icon: "kg-icon-art.svg" },
  { id: "adventure", label: "Abenteuer & Outdoor", icon: "kg-icon-adventure.svg" },
  { id: "planning", label: "Reiseplanung", icon: "kg-icon-planning.svg" },
];

const REGIONS = ["Panhandle", "Nordflorida", "Zentralflorida", "Südflorida", "Florida Keys", "Allgemein"];

const ENTRIES = [
  { id: "b1", cat: "beaches", region: "Zentralflorida", name: "Clearwater Beach", icon: "", lat: 27.977, lon: -82.827,
    desc: "Feiner, fast weißer Quarzsand an der Golfküste und ein besonders ruhiges, flaches Wasser. Der Pier 60 ist abends Treffpunkt für die Sonnenuntergangs-Feier mit Straßenkünstlern.",
    tip: "Am späten Nachmittag anreisen und den Sonnenuntergang am Pier abwarten.", tags: ["Strand", "Familien", "Sonnenuntergang"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b2", cat: "beaches", region: "Zentralflorida", name: "Siesta Key Beach", icon: "", lat: 27.263, lon: -82.539,
    desc: "Der Sand besteht fast vollständig aus Quarz und bleibt dadurch auch in praller Sonne angenehm kühl unter den Füßen. Bei Sarasota gelegen und regelmäßig unter den bestbewerteten Stränden der USA gelistet.",
    tip: "Kostenlose Parkplätze füllen sich vormittags schnell – früh kommen.", tags: ["Strand", "Familien"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b3", cat: "beaches", region: "Südflorida", name: "South Beach (Miami Beach)", icon: "", lat: 25.782, lon: -80.130,
    desc: "Breite Promenade vor der Kulisse des Art-Deco-Viertels, bunt bemalte Rettungsschwimmertürme und ganzjährig lebhaftes Treiben. Eher Bühne als Ruheort.",
    tip: "Die Rettungsschwimmertürme entlang Ocean Drive sind ein eigenes Fotomotiv.", tags: ["Strand", "Architektur", "Nightlife"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b4", cat: "beaches", region: "Zentralflorida", name: "Anna Maria Island", icon: "", lat: 27.530, lon: -82.729,
    desc: "Kleine, kaum bebaute Inselgemeinde nördlich von Sarasota mit lokalem Charakter statt Hochhauskulisse. Fahrradwege verbinden die drei Ortsteile.",
    tip: "Der kostenlose Inselbus (Trolley) fährt die ganze Insel ab.", tags: ["Strand", "Ruhig", "Fahrrad"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b5", cat: "beaches", region: "Florida Keys", name: "Bahia Honda State Park", icon: "", lat: 24.657, lon: -81.269,
    desc: "Türkisfarbenes Wasser und Blick auf die Reste einer historischen Eisenbahnbrücke. Gilt als einer der schönsten Strände der Florida Keys mit gutem Schnorchelrevier.",
    tip: "Schnorchelausrüstung vor Ort leihbar, das Riff liegt per Boot-Tour weiter draußen.", tags: ["Strand", "Schnorcheln", "Natur"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b6", cat: "beaches", region: "Zentralflorida", name: "Fort De Soto Park", icon: "", lat: 27.617, lon: -82.741,
    desc: "Vorgelagerte Inselkette bei St. Petersburg mit mehreren Stränden, einem historischen Fort und einem der artenreichsten Vogelbeobachtungsgebiete Floridas.",
    tip: "Der Nordstrand ist ruhiger, der Gulf-Strand belebter.", tags: ["Strand", "Vögel", "Geschichte"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b7", cat: "beaches", region: "Südflorida", name: "Everglades National Park", icon: "", lat: 25.396, lon: -80.680,
    desc: "Riesiges subtropisches Feuchtgebiet mit Mangroven, Sägegras-Prärien und freilebenden Alligatoren. Erschließbar über Wanderwege, Airboat-Touren und Kanuroute.",
    tip: "Der Anhinga Trail bei Royal Palm ist der zuverlässigste Ort für Alligator-Sichtungen aus nächster Nähe.", tags: ["Nationalpark", "Wildtiere", "Wandern"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b8", cat: "beaches", region: "Südflorida", name: "Biscayne National Park", icon: "", lat: 25.465, lon: -80.208,
    desc: "Zu rund 95 % Wasserfläche mit vorgelagertem Korallenriff. Zugänglich nur per Boot, beliebt für Schnorcheln und Tauchen ab Homestead.",
    tip: "Bootstouren beim Visitor Center vorab reservieren, Kapazitäten sind begrenzt.", tags: ["Nationalpark", "Schnorcheln", "Tauchen"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b9", cat: "beaches", region: "Südflorida", name: "Big Cypress National Preserve", icon: "", lat: 25.821, lon: -81.033,
    desc: "Zypressensumpfland direkt nördlich der Everglades mit landschaftlich reizvollem Scenic Drive und guten Chancen auf Wildtierbeobachtungen abseits der Touristenrouten.",
    tip: "Der Loop Road Scenic Drive ist unbefestigt – langsam fahren, dafür naturnaher.", tags: ["Natur", "Wildtiere", "Autotour"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b10", cat: "beaches", region: "Nordflorida", name: "Crystal River", icon: "", lat: 28.902, lon: -82.593,
    desc: "Winterrefugium für Rundschwanzseekühe (Manatees), die im warmen Quellwasser Zuflucht vor kaltem Golfwasser suchen. Begegnungen im Wasser sind unter strengen Regeln erlaubt.",
    tip: "Beste Sichtungszeit ist früh morgens zwischen November und März.", tags: ["Wildtiere", "Schwimmen", "Manatees"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b11", cat: "beaches", region: "Nordflorida", name: "Wakulla Springs State Park", icon: "", lat: 30.234, lon: -84.302,
    desc: "Eine der größten und tiefsten Süßwasserquellen der Welt mit glasklarem Wasser. Glasbodenboot-Touren zeigen Fischschwärme und gelegentlich Alligatoren.",
    tip: "Schwimmen ist nur im ausgewiesenen, abgesperrten Bereich erlaubt.", tags: ["Quelle", "Bootstour", "Natur"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b12", cat: "beaches", region: "Florida Keys", name: "Dry Tortugas National Park", icon: "", lat: 24.628, lon: -82.873,
    desc: "Entlegene Inselgruppe rund 110 Kilometer vor Key West, erreichbar nur per Fähre oder Wasserflugzeug. Zentrum ist das gewaltige Seefestungsbauwerk Fort Jefferson.",
    tip: "Frühzeitig buchen – die Fähre hat begrenzte Plätze und ist oft Wochen im Voraus ausgebucht.", tags: ["Nationalpark", "Geschichte", "Abgelegen"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },

  { id: "c1", cat: "cities", region: "Südflorida", name: "Miami", icon: "", lat: 25.7617, lon: -80.1918,
    desc: "Das Art-Deco-Viertel South Beach, die Streetart-Galerien von Wynwood Walls und das kubanisch geprägte Little Havana zeigen drei völlig unterschiedliche Gesichter derselben Stadt.",
    tip: "Wynwood lohnt sich besonders am späten Nachmittag im weichen Licht für Fotos.", tags: ["Architektur", "Streetart", "Kulinarik"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c2", cat: "cities", region: "Zentralflorida", name: "Orlando (abseits der Parks)", icon: "", lat: 28.5383, lon: -81.3792,
    desc: "Rund um den Lake Eola im Zentrum liegt eine ruhige Parklandschaft mit Skyline-Blick, ergänzt durch eine wachsende Craft-Beer- und Restaurantszene fernab der Parkgelände.",
    tip: "Sonntags findet am Lake Eola ein Farmers Market statt.", tags: ["Stadt", "Entspannung"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c3", cat: "cities", region: "Zentralflorida", name: "Tampa", icon: "", lat: 27.9506, lon: -82.4572,
    desc: "Ybor City, das historische Zigarrenmacher-Viertel, prägt mit spanisch-kubanischer Architektur das Stadtbild. Der Riverwalk verbindet Museen, Aquarium und Parks entlang des Flusses.",
    tip: "Ybor City ist abends belebt, tagsüber eher ruhig und gut zum Bummeln.", tags: ["Geschichte", "Architektur"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c4", cat: "cities", region: "Nordflorida", name: "St. Augustine", icon: "", lat: 29.8947, lon: -81.3145,
    desc: "Gilt als älteste durchgehend besiedelte europäische Gründung der heutigen USA. Die spanische Festung Castillo de San Marcos und die Altstadtgassen prägen das historische Zentrum.",
    tip: "Die Festung bietet einen guten Überblick über die gesamte Bucht.", tags: ["Geschichte", "Architektur"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c5", cat: "cities", region: "Florida Keys", name: "Key West", icon: "", lat: 24.5551, lon: -81.7800,
    desc: "Südlichster Punkt der kontinentalen USA mit karibischem Flair. Die Duval Street und die abendliche Sonnenuntergangsfeier am Mallory Square gehören zum festen Programm.",
    tip: "Der Highway dorthin (Overseas Highway) ist selbst schon Teil der Attraktion.", tags: ["Insel", "Nightlife", "Sonnenuntergang"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c6", cat: "cities", region: "Zentralflorida", name: "Sarasota", icon: "", lat: 27.3364, lon: -82.5307,
    desc: "Kunststadt mit Zirkus-Erbe: Der Ringling-Museumskomplex vereint Kunstmuseum, historische Villa und Zirkusmuseum auf einem weitläufigen Gelände am Wasser.",
    tip: "Für den gesamten Ringling-Komplex einen halben Tag einplanen.", tags: ["Kunst", "Museum", "Geschichte"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c7", cat: "cities", region: "Zentralflorida", name: "St. Petersburg", icon: "", lat: 27.7676, lon: -82.6403,
    desc: "Die Innenstadt ist voller großformatiger Wandgemälde, ergänzt durch das Dalí-Museum mit einer der größten Sammlungen des Künstlers außerhalb Spaniens.",
    tip: "Ein Spaziergang durch das Warehouse Arts District zeigt die Murals am dichtesten.", tags: ["Streetart", "Museum"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c8", cat: "cities", region: "Südflorida", name: "Palm Beach", icon: "", lat: 26.7056, lon: -80.0364,
    desc: "Mondäne Villenarchitektur und die Einkaufsmeile Worth Avenue prägen diesen Ort mit einer der höchsten Dichte historischer Anwesen im Bundesstaat.",
    tip: "Worth Avenue eignet sich gut für einen Spaziergang auch ohne Einkaufsabsicht.", tags: ["Architektur", "Shopping"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c9", cat: "cities", region: "Panhandle", name: "Pensacola", icon: "", lat: 30.4213, lon: -87.2169,
    desc: "Historisches Viertel mit spanisch-kolonialer Vergangenheit und das National Naval Aviation Museum mit einer umfangreichen Sammlung historischer Militärflugzeuge.",
    tip: "Die weißen Sandstrände am Pensacola Beach zählen zu den feinsten am Golf.", tags: ["Geschichte", "Museum", "Strand"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c10", cat: "cities", region: "Südflorida", name: "Fort Lauderdale", icon: "", lat: 26.1224, lon: -80.1373,
    desc: "Ein dichtes Netz aus Kanälen hat der Stadt den Beinamen 'Venedig Amerikas' eingebracht. Wasser-Taxis sind hier ein reguläres Fortbewegungsmittel.",
    tip: "Eine Wasser-Taxi-Fahrt ist eine günstige Alternative zur klassischen Stadtrundfahrt.", tags: ["Kanäle", "Boot"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },

  { id: "p1", cat: "parks", region: "Zentralflorida", name: "Märchenschloss-Themenpark", icon: "", lat: 28.4177, lon: -81.5812,
    desc: "Der älteste und meistbesuchte Themenpark der Region, aufgebaut um ein zentrales Schloss mit mehreren angrenzenden Themenwelten.",
    tip: "Die Frühöffnungszeiten für Übernachtungsgäste im Resort nutzen, um Wartezeiten zu umgehen.", tags: ["Familien", "Fahrgeschäfte"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p2", cat: "parks", region: "Zentralflorida", name: "Weltausstellungs-Themenpark", icon: "", lat: 28.3747, lon: -81.5494,
    desc: "Ursprünglich als permanente Weltausstellung konzipiert: ein Bereich mit Pavillons verschiedener Länder trifft auf einen Bereich rund um Zukunftstechnologie und Wissenschaft.",
    tip: "Der Länder-Rundgang eignet sich gut, um internationale Küche in kleinen Portionen zu probieren.", tags: ["Kulinarik", "International"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p3", cat: "parks", region: "Zentralflorida", name: "Film-Themenpark", icon: "", lat: 28.3577, lon: -81.5583,
    desc: "Themenpark rund um Film- und Fernsehgeschichte, mit einem umfangreichen, immersiv gestalteten Bereich zu einem bekannten Weltraum-Science-Fiction-Universum.",
    tip: "Reservierungen für die beliebtesten Attraktionen frühzeitig über die offizielle App sichern.", tags: ["Film", "Fahrgeschäfte"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p4", cat: "parks", region: "Zentralflorida", name: "Tier- und Safari-Themenpark", icon: "", lat: 28.3553, lon: -81.5901,
    desc: "Kombination aus Themenpark und Tierpark mit einer ausgedehnten Safari-Fahrt durch eine nachgebildete afrikanische Savannenlandschaft.",
    tip: "Die Safari-Tiere sind am frühen Morgen am aktivsten.", tags: ["Tiere", "Familien"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p5", cat: "parks", region: "Zentralflorida", name: "Abenteuer-Themenpark", icon: "", lat: 28.4722, lon: -81.4691,
    desc: "In mehrere Inselthemen gegliederter Park, unter anderem mit einem ausgedehnten, detailreich gestalteten Bereich rund um eine bekannte Zauberer-Buchwelt-Verfilmung.",
    tip: "Der Themenbereich ist morgens direkt bei Öffnung am wenigsten überlaufen.", tags: ["Fahrgeschäfte", "Familien"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p6", cat: "parks", region: "Zentralflorida", name: "Vulkan-Wasserpark", icon: "", lat: 28.4622, lon: -81.4547,
    desc: "Wasserpark, dessen Attraktionen um einen zentralen, begehbaren künstlichen Vulkan angeordnet sind, inklusive Wellenbecken und Rutschen unterschiedlicher Intensität.",
    tip: "Das virtuelle Warteschlangensystem vor Ort direkt bei Ankunft aktivieren.", tags: ["Wasserpark", "Familien"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p7", cat: "parks", region: "Zentralflorida", name: "Safari-Achterbahnpark", icon: "", lat: 28.0378, lon: -82.4198,
    desc: "Kombiniert Achterbahnen im oberen Nervenkitzel-Segment mit einem afrikanisch inspirierten Tierpark und einer eigenen Safari-Fläche.",
    tip: "Für Achterbahnfans und Tierfreunde gleichermaßen geeignet – ein ganzer Tag lohnt sich.", tags: ["Achterbahnen", "Tiere"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p8", cat: "parks", region: "Zentralflorida", name: "Raumfahrt-Besucherzentrum", icon: "", lat: 28.5236, lon: -80.6810,
    desc: "Besucherzentrum des historischen Weltraumbahnhofs mit Raketengarten, ausgestellten Space-Shuttle-Exponaten und wechselndem Besucherprogramm zu aktuellen Starts.",
    tip: "Vorab online prüfen, ob während des Besuchs ein Raketenstart geplant ist.", tags: ["Raumfahrt", "Geschichte"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },

  { id: "t1", cat: "planning", region: "Allgemein", name: "Beste Reisezeit", icon: "", lat: null, lon: null,
    desc: "Die Trockenzeit von November bis April gilt mit milderen Temperaturen und wenig Niederschlag als angenehmste Reisezeit. Von Mai bis Oktober ist es feuchtheiß mit häufigen Nachmittagsschauern.",
    tip: "Für eine Mischung aus günstigeren Preisen und noch gutem Wetter eignen sich April und November.", tags: ["Klima", "Timing"] },
  { id: "t2", cat: "planning", region: "Allgemein", name: "Hurrikansaison", icon: "", lat: null, lon: null,
    desc: "Die offizielle Atlantik-Hurrikansaison läuft von Juni bis November, mit statistischem Höhepunkt zwischen August und Oktober. Warnsysteme und Vorbereitung sind in Florida gut etabliert.",
    tip: "Reiseversicherung mit Sturm-Rücktrittsschutz für Reisen in dieser Zeit prüfen.", tags: ["Klima", "Sicherheit"] },
  { id: "t3", cat: "planning", region: "Allgemein", name: "Mietwagen & Verkehr", icon: "", lat: null, lon: null,
    desc: "Es herrscht Rechtsverkehr, das Highway-Netz ist gut ausgebaut. Viele Mautstrecken werden über elektronische Transponder oder Kennzeichenerfassung abgerechnet statt an Schranken.",
    tip: "Beim Mietwagen direkt nach einem Maut-Paket (Toll Pass) fragen, das spart Ärger im Nachhinein.", tags: ["Auto", "Praktisch"] },
  { id: "t4", cat: "planning", region: "Allgemein", name: "Einreisebestimmungen", icon: "", lat: null, lon: null,
    desc: "Für kurze touristische Aufenthalte benötigen viele Staatsangehörige eine vorab online beantragte Einreisegenehmigung. Die genauen Voraussetzungen hängen von der eigenen Staatsangehörigkeit ab.",
    tip: "Formalitäten frühzeitig und ausschließlich über offizielle Regierungswege klären, nie über Drittanbieter-Seiten.", tags: ["Formalitäten"] },
  { id: "t5", cat: "planning", region: "Allgemein", name: "Sonnenschutz & Gesundheit", icon: "", lat: null, lon: null,
    desc: "Der UV-Index liegt fast ganzjährig sehr hoch, dazu kommen hohe Luftfeuchtigkeit und in feuchten Gebieten Mücken. Ausreichend Sonnenschutz und Insektenschutzmittel gehören ins Reisegepäck.",
    tip: "Wasserfester Sonnenschutz ist bei Wasseraktivitäten Pflicht, nicht nur Empfehlung.", tags: ["Gesundheit"] },
  { id: "t6", cat: "planning", region: "Allgemein", name: "Budget-Tipps", icon: "", lat: null, lon: null,
    desc: "Nebensaison, Mehrtages-Pässe für Themenparks und Selbstverpflegung über Ferienwohnungen mit Küche senken die Reisekosten spürbar gegenüber der Hauptsaison.",
    tip: "Getränke und Snacks vorab im Supermarkt kaufen statt in den Parks – der Preisunterschied ist erheblich.", tags: ["Kosten"] },
  { id: "t7", cat: "planning", region: "Allgemein", name: "Regionen-Überblick", icon: "", lat: null, lon: null,
    desc: "Florida gliedert sich grob in den Panhandle im Nordwesten, Nordflorida, das zentrale Themenpark-Gebiet um Orlando, das tropische Südflorida sowie die vorgelagerten Florida Keys.",
    tip: "Die Entfernungen sind größer als sie auf der Karte wirken – realistisch planen statt zu viele Regionen kombinieren.", tags: ["Orientierung"] },
  { id: "t8", cat: "planning", region: "Allgemein", name: "Packliste-Hinweise", icon: "", lat: null, lon: null,
    desc: "Leichte, atmungsaktive Kleidung, eine leichte Regenjacke für plötzliche Nachmittagsschauer sowie Bade- und Schnorchelausrüstung decken die meisten Situationen ab.",
    tip: "Eine leichte Fleecejacke einpacken – Innenräume und Themenparks kühlen oft stark herunter.", tags: ["Gepäck"] },
  { id: "t9", cat: "planning", region: "Allgemein", name: "Trinkgeld-Kultur", icon: "", lat: null, lon: null,
    desc: "In Restaurants, Taxis und bei vielen Dienstleistungen ist Trinkgeld fester Bestandteil der Bezahlkultur und nicht optional, da es oft einen Teil des Lohns ausmacht.",
    tip: "Als grobe Richtschnur im Restaurant gelten häufig 18–20 % der Rechnungssumme.", tags: ["Kultur", "Praktisch"] },
  { id: "t10", cat: "planning", region: "Allgemein", name: "Zeitzonen in Florida", icon: "", lat: null, lon: null,
    desc: "Der Großteil des Bundesstaates liegt in der Eastern Time Zone, der westliche Panhandle ab etwa dem Apalachicola River jedoch in der Central Time Zone, eine Stunde dahinter.",
    tip: "Bei Terminen im Panhandle die abweichende Zeitzone im Blick behalten.", tags: ["Orientierung"] },

  { id: "b13", cat: "beaches", region: "Zentralflorida", name: "Cocoa Beach", icon: "", lat: 28.3200, lon: -80.6076,
    desc: "Bekannter Surf-Spot an der sogenannten Space Coast, direkt in der Nähe des dortigen Raumfahrt-Besucherzentrums. Auch für Surf-Anfänger gut geeignet, mit mehreren Surfschulen vor Ort.",
    tip: "Der Pier eignet sich gut, um Surfern beim Wellenreiten zuzusehen, ohne selbst nass zu werden.", tags: ["Strand", "Surfen"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b14", cat: "beaches", region: "Florida Keys", name: "John Pennekamp Coral Reef State Park", icon: "", lat: 25.1300, lon: -80.4064,
    desc: "Der erste Unterwasser-Park der USA, direkt bei Key Largo. Schnorchel- und Tauchtouren führen zu vorgelagerten Korallenriffen mit hoher Sichtweite.",
    tip: "Glasbodenboot-Touren sind eine gute Alternative, wenn Schnorcheln nicht infrage kommt.", tags: ["Schnorcheln", "Tauchen", "Nationalpark"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b15", cat: "beaches", region: "Südflorida", name: "Sanibel Island", icon: "", lat: 26.4526, lon: -82.1206,
    desc: "Insel vor Fort Myers, bekannt für eine außergewöhnlich hohe Dichte an Muscheln am Strand – ein beliebtes Ziel für Muschelsammler:innen aus aller Welt.",
    tip: "Bei Ebbe kurz nach Sonnenaufgang ist die Muschelausbeute am größten.", tags: ["Strand", "Muscheln", "Ruhig"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b16", cat: "beaches", region: "Südflorida", name: "Blowing Rocks Preserve", icon: "", lat: 27.0286, lon: -80.0817,
    desc: "Naturschutzgebiet auf Jupiter Island mit einer ungewöhnlichen Kalkstein-Küstenformation. Bei Flut und kräftigem Wellengang schießt Gischt spektakulär durch Felslöcher.",
    tip: "Für das Gischt-Spektakel den Zeitpunkt der Flut vorher online prüfen.", tags: ["Natur", "Felsformation"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Kostenlos bis günstig" },
  { id: "b17", cat: "beaches", region: "Zentralflorida", name: "Caladesi Island State Park", icon: "", lat: 28.0334, lon: -82.8271,
    desc: "Nur per Fähre oder eigenem Boot erreichbare, weitgehend unbebaute Insel vor Dunedin mit feinem Sand und ruhigen Buchten.",
    tip: "Fährfahrplan vorab prüfen — die letzte Rückfahrt am Nachmittag verpasst man ungern.", tags: ["Insel", "Ruhig", "Naturbelassen"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Günstig (Fährticket)" },
  { id: "b18", cat: "beaches", region: "Zentralflorida", name: "Sebastian Inlet State Park", icon: "", lat: 27.8597, lon: -80.4483,
    desc: "Einer der bekanntesten Surf-Spots Floridas an der Space Coast, zugleich beliebt zum Angeln von der Mole aus.",
    tip: "Frühmorgens ist die Wellenqualität für Anfänger meist am angenehmsten.", tags: ["Surfen", "Angeln", "Strand"],
    bestTime: "Herbst bis Frühling für größere Wellen, Sommer ruhiger", costHint: "Günstig" },
  { id: "b19", cat: "beaches", region: "Südflorida", name: "Cayo Costa State Park", icon: "", lat: 26.7118, lon: -82.2557,
    desc: "Unerschlossene Barriereinsel bei Fort Myers, nur per Boot oder Fähre erreichbar, mit kilometerlangen menschenleeren Stränden.",
    tip: "Kein Festland-Anschluss — Verpflegung und Wasser selbst mitbringen.", tags: ["Insel", "Naturbelassen", "Abgelegen"],
    bestTime: "Ganzjährig, November bis April angenehmer", costHint: "Günstig (Fährticket)" },
  { id: "b20", cat: "beaches", region: "Zentralflorida", name: "Honeymoon Island State Park", icon: "", lat: 28.0611, lon: -82.8263,
    desc: "Vorgelagerte Insel bei Dunedin mit einem der wenigen verbliebenen Kiefernwälder der Golfküste direkt hinter dem Strand.",
    tip: "Der Nature Trail eignet sich gut für einen kurzen Spaziergang abseits des Strandes.", tags: ["Strand", "Wandern", "Natur"],
    bestTime: "Ganzjährig, November bis April meist trockener und angenehmer", costHint: "Günstig (Fahrzeuggebühr)" },

  { id: "c11", cat: "cities", region: "Südflorida", name: "Naples", icon: "", lat: 26.1420, lon: -81.7948,
    desc: "Elegante Golfküstenstadt mit gepflegter Innenstadt, zahlreichen Kunstgalerien und einem der saubersten Strände Floridas direkt am Ortskern.",
    tip: "Der Fußgängerbereich der Fifth Avenue South eignet sich gut für einen Abendspaziergang.", tags: ["Architektur", "Kunst", "Strand"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c12", cat: "cities", region: "Zentralflorida", name: "Winter Park", icon: "", lat: 28.5999, lon: -81.3392,
    desc: "Kleinstädtischer Vorort von Orlando mit der bekannten Einkaufs- und Restaurantmeile Park Avenue sowie einer beliebten Bootstour durch die verbundenen Seen und Kanäle.",
    tip: "Die Scenic Boat Tour dauert etwa eine Stunde und führt an prächtigen Ufervillen vorbei.", tags: ["Bootstour", "Shopping", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c13", cat: "cities", region: "Südflorida", name: "Coral Gables", icon: "", lat: 25.7215, lon: -80.2684,
    desc: "Sorgfältig geplanter Stadtteil bei Miami im Stil der spanisch-mediterranen Architektur der 1920er Jahre, mit einem berühmten historischen öffentlichen Schwimmbad in einem ehemaligen Steinbruch.",
    tip: "Das Schwimmbad ist ein öffentliches Bad und keine gewöhnliche Sehenswürdigkeit zum bloßen Anschauen — Badesachen einplanen.", tags: ["Architektur", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel" },
  { id: "c14", cat: "cities", region: "Zentralflorida", name: "Dunedin", icon: "", lat: 28.0197, lon: -82.7754,
    desc: "Kleinstadt mit schottischen Wurzeln an der Golfküste, bekannt für ihre begehbare Innenstadt, Golfwagen-Kultur und den Anschluss an einen beliebten Rad-/Wanderweg.",
    tip: "Der Rad-/Wanderweg verbindet Dunedin bequem mit Nachbarorten — auch ohne eigenes Fahrrad gibt es Verleihstationen.", tags: ["Ruhig", "Radfahren"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig" },
  { id: "c15", cat: "cities", region: "Nordflorida", name: "DeLand", icon: "", lat: 29.0283, lon: -81.3009,
    desc: "Historisches Universitätsstädtchen mit gut erhaltener Innenstadt und Sitz der ältesten privaten Universität Floridas.",
    tip: "Die historische Innenstadt lässt sich gut zu Fuß erkunden, viele Gebäude stammen aus dem späten 19. Jahrhundert.", tags: ["Architektur", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig" },

  { id: "p9", cat: "parks", region: "Zentralflorida", name: "Bausteine-Themenpark", icon: "", lat: 27.9925, lon: -81.6971,
    desc: "Auf dem Gelände eines ehemaligen botanischen Gartens bei Winter Haven gelegener Themenpark rund um bunte Bausteine, mit eigenem Wasserpark und Miniatur-Nachbauten bekannter US-Städte.",
    tip: "Der angeschlossene Wasserpark ist im Ticket oft nicht automatisch enthalten – vorab prüfen.", tags: ["Familien", "Fahrgeschäfte"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p10", cat: "parks", region: "Zentralflorida", name: "Meerestier-Themenpark", icon: "", lat: 28.4111, lon: -81.4620,
    desc: "Themenpark mit Fokus auf Meerestieren, Achterbahnen und Shows. Beteiligt sich auch an Rettungs- und Rehabilitationsprogrammen für verletzte Meerestiere.",
    tip: "Die Hinter-den-Kulissen-Touren zu den Tierrettungsprogrammen sind gesondert buchbar.", tags: ["Tiere", "Achterbahnen"],
    bestTime: "Nebensaison (Januar/Februar, September/Oktober) meist weniger überlaufen", costHint: "Gehoben" },
  { id: "p11", cat: "parks", region: "Zentralflorida", name: "Aussichtsrad-Vergnügungskomplex", icon: "", lat: 28.4453, lon: -81.4692,
    desc: "Unterhaltungskomplex an der International Drive rund um ein 122 Meter hohes Aussichtsrad mit Blick über Orlando, ergänzt durch Mini-Golf, ein Wachsfigurenkabinett und ein Aquarium.",
    tip: "Bei klarer Sicht lohnt sich eine Fahrt kurz vor Sonnenuntergang besonders.", tags: ["Aussicht", "Familien"],
    bestTime: "Ganzjährig, abends für die Aussicht besonders reizvoll", costHint: "Mittel" },
  { id: "p12", cat: "parks", region: "Zentralflorida", name: "Jahrmarkt-Freizeitpark", icon: "", lat: 28.3479, lon: -81.4619,
    desc: "Familiengeführter Freizeitpark mit klassischen Jahrmarkt-Fahrgeschäften, mehreren Go-Kart-Bahnen auf verschiedenen Ebenen und freiem Eintritt zum Gelände selbst.",
    tip: "Der Eintritt zum Gelände ist kostenlos — bezahlt wird nur pro Fahrgeschäft oder über ein Tagesarmband.", tags: ["Familien", "Fahrgeschäfte"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig bis mittel (nach Wahl)" },
  { id: "p13", cat: "parks", region: "Zentralflorida", name: "Alligatorenpark", icon: "", lat: 28.3719, lon: -81.3970,
    desc: "Seit den 1940er-Jahren bestehender, bewusst bodenständiger Park rund um Alligatoren und Krokodile, mit Shows, einem Zipline-Parcours über den Sumpfgehegen und einem Streichelzoo.",
    tip: "Die „Gator Wrestlin’”-Show ist eine traditionelle, augenzwinkernde Florida-Institution und keine ernsthafte Tierquälerei-Darstellung.", tags: ["Tiere", "Familien"],
    bestTime: "Ganzjährig gut besuchbar, Vormittage oft angenehmer temperiert", costHint: "Mittel" },

  { id: "f1", cat: "food", region: "Florida Keys", name: "Key Lime Pie", icon: "", lat: null, lon: null,
    desc: "Die inoffizielle Nachspeise Floridas: ein cremiger, säuerlicher Kuchen aus Limettensaft der kleinen Key-Limette, meist auf Kekskrümel-Boden und mit Baisertopping.",
    tip: "Original wird die Sorte mit den kleinen, gelblichen Key-Limetten gemacht, nicht mit gewöhnlichen grünen Limetten.", tags: ["Süßspeise", "Regional"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f2", cat: "food", region: "Südflorida", name: "Stone Crab Claws", icon: "", lat: null, lon: null,
    desc: "Regionale Spezialität, bei der nur eine Schere der Steinkrabbe geerntet wird – das Tier selbst wird lebend zurückgesetzt und regeneriert die Schere. Saison ist etwa Oktober bis Mai.",
    tip: "Werden traditionell kalt mit einer Senf-Mayonnaise-Sauce serviert.", tags: ["Meeresfrüchte", "Saisonal"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f3", cat: "food", region: "Zentralflorida", name: "Cuban Sandwich", icon: "", lat: null, lon: null,
    desc: "Geschichtete, gepresste Sandwich-Spezialität mit Ursprung im Zigarrenarbeiter-Viertel Ybor City in Tampa: Schinken, Schweinebraten, Käse, Pickles und Senf in gepresstem Brot.",
    tip: "In Tampa wird oft zusätzlich Salami hinzugefügt – eine lokale Abwandlung des Miami-Originals.", tags: ["Sandwich", "Regional"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f4", cat: "food", region: "Allgemein", name: "Golfküsten-Garnelen", icon: "", lat: null, lon: null,
    desc: "Frische Garnelen aus dem Golf von Mexiko gehören an der Westküste Floridas zu den kulinarischen Klassikern, oft einfach gegrillt oder in Fischbuden direkt am Hafen serviert.",
    tip: "Fischereihäfen wie in Tarpon Springs oder Naples bieten oft die frischeste Ware.", tags: ["Meeresfrüchte", "Regional"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f5", cat: "food", region: "Nordflorida", name: "Boiled Peanuts", icon: "", lat: null, lon: null,
    desc: "In Salzwasser gekochte, noch grüne Erdnüsse – ein typischer Südstaaten-Snack, der oft an Straßenständen entlang der Highways im nördlichen Florida verkauft wird.",
    tip: "Die Konsistenz ist weich statt knackig – das überrascht viele beim ersten Probieren.", tags: ["Snack", "Regional"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f6", cat: "food", region: "Allgemein", name: "Food Trucks & Fischbuden", icon: "", lat: null, lon: null,
    desc: "Entlang vieler Küstenorte haben sich lockere Food-Truck- und Fischbuden-Szenen etabliert, oft mit bester Aussicht und entspannter Atmosphäre statt klassischem Restaurant-Ambiente.",
    tip: "Bewertungsportale kurz vor Ort checken, da sich die Truck-Standorte häufig ändern.", tags: ["Streetfood", "Lockere Atmosphäre"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f7", cat: "food", region: "Allgemein", name: "Farmers Markets", icon: "", lat: null, lon: null,
    desc: "Wochenmärkte mit frischem Obst, insbesondere Zitrusfrüchten, sind in vielen Städten und Gemeinden fester Bestandteil des Wochenendes und ein guter Ort für lokale Spezialitäten.",
    tip: "Öffnungszeiten variieren je nach Ort meist samstagvormittags – vorher online prüfen.", tags: ["Markt", "Obst"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f8", cat: "food", region: "Zentralflorida", name: "Craft-Brauereien", icon: "", lat: null, lon: null,
    desc: "Besonders in Orlando und Tampa hat sich eine wachsende Craft-Beer-Szene mit unabhängigen Brauereien und Verkostungsräumen etabliert.",
    tip: "Viele Brauereien bieten Kurzführungen mit anschließender Verkostung an.", tags: ["Bier", "Nightlife"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f9", cat: "food", region: "Südflorida", name: "Alligator Bites", icon: "", lat: null, lon: null,
    desc: "Frittierte Stücke von Alligatorfleisch sind eine regionale Spezialität, die vor allem in Südflorida und rund um die Everglades auf vielen Speisekarten zu finden ist.",
    tip: "Geschmacklich und in der Konsistenz oft mit Hähnchenfleisch verglichen.", tags: ["Regional", "Exotisch"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f10", cat: "food", region: "Zentralflorida", name: "Frischer Orangensaft", icon: "", lat: null, lon: null,
    desc: "Florida ist einer der weltweit größten Anbauregionen für Orangen. Frisch gepresster Saft direkt an Straßenständen oder auf Zitrusplantagen ist entsprechend allgegenwärtig.",
    tip: "Manche Plantagen bieten Führungen mit Verkostung verschiedener Zitrussorten an.", tags: ["Getränk", "Regional"],
    bestTime: "Ganzjährig verfügbar, sofern im Text nicht anders vermerkt", costHint: "Günstig bis mittel" },
  { id: "f11", cat: "food", region: "Zentralflorida", name: "Grouper Sandwich", icon: "", lat: null, lon: null,
    desc: "Gebratenes oder gegrilltes Zackenbarsch-Filet im Brötchen, an der Golfküste ein fester Bestandteil praktisch jeder Speisekarte in Strandnähe.",
    tip: "„Blackened” (scharf angebraten mit Gewürzkruste) ist eine beliebte Zubereitungsart neben „grilled” oder „fried”.", tags: ["Fisch", "Regional"],
    bestTime: "Ganzjährig verfügbar", costHint: "Mittel" },
  { id: "f12", cat: "food", region: "Südflorida", name: "Cafecito (kubanischer Kaffee)", icon: "", lat: null, lon: null,
    desc: "Stark gesüßter, espressoartiger Kaffee aus der kubanisch geprägten Kaffeehaus-Kultur Miamis, oft im Stehen an einem Fenster-Tresen (Ventanita) getrunken.",
    tip: "Ein „cortadito” ist dieselbe Kaffeesorte mit etwas aufgeschäumter Milch, für alle, denen Cafecito pur zu süß und stark ist.", tags: ["Getränk", "Regional"],
    bestTime: "Ganzjährig verfügbar", costHint: "Günstig" },

  { id: "t11", cat: "planning", region: "Allgemein", name: "Notrufnummern", icon: "", lat: null, lon: null,
    desc: "Die landesweite Notrufnummer für Polizei, Feuerwehr und Rettungsdienst ist 911, erreichbar von jedem Telefon. Für Vergiftungsfälle gibt es zusätzlich eine spezialisierte Giftnotrufzentrale.",
    tip: "Poison Control (Giftnotruf) ist unter 1-800-222-1222 rund um die Uhr erreichbar.", tags: ["Notfall", "Sicherheit"] },
  { id: "t12", cat: "planning", region: "Allgemein", name: "Deutsche Auslandsvertretung", icon: "", lat: null, lon: null,
    desc: "Für deutsche Staatsangehörige ist in Florida in der Regel das Generalkonsulat in Miami zuständig, etwa bei Passverlust oder anderen konsularischen Notfällen.",
    tip: "Aktuelle Kontaktdaten und Öffnungszeiten vor Abreise auf der Website des Auswärtigen Amts prüfen, da sich diese ändern können.", tags: ["Notfall", "Formalitäten"] },
  { id: "t13", cat: "planning", region: "Allgemein", name: "Stromversorgung & Adapter", icon: "", lat: null, lon: null,
    desc: "In den USA liegt die Netzspannung bei 120 Volt und 60 Hertz, abweichend vom europäischen Standard. Steckdosen sind vom Typ A/B mit flachen Stiften.",
    tip: "Ladegeräte für Handy/Laptop vertragen meist beide Spannungen (100–240V) – nur ein Steckadapter ohne Spannungswandler ist meist ausreichend, bei Föhn & Co. aber vorher das Kleingedruckte prüfen.", tags: ["Praktisch", "Technik"] },
  { id: "t14", cat: "planning", region: "Allgemein", name: "Verkehrsregeln-Basics", icon: "", lat: null, lon: null,
    desc: "Rechtsabbiegen bei Rot ist grundsätzlich erlaubt, sofern nicht anders ausgeschildert. Hält ein Schulbus mit ausgeklapptem Stoppschild, müssen Fahrzeuge aus beiden Richtungen anhalten.",
    tip: "Handynutzung am Steuer ist in vielen Countys verboten oder eingeschränkt – Freisprechfunktion nutzen.", tags: ["Auto", "Sicherheit"] },
  { id: "t15", cat: "planning", region: "Allgemein", name: "Unwetter-Warnungen", icon: "", lat: null, lon: null,
    desc: "Offizielle Wetterwarnungen (etwa bei Hurrikanen oder Tornados) werden in den USA über das National Weather Service verbreitet und sind auch über verbreitete Wetter-Apps abrufbar.",
    tip: "Eine lokale Wetter-App mit Push-Benachrichtigungen für Unwetterwarnungen vor Reisebeginn installieren.", tags: ["Sicherheit", "Klima"] },

  { id: "t16", cat: "planning", region: "Nordflorida", name: "Spanische Kolonialgeschichte", icon: "", lat: null, lon: null,
    desc: "Florida stand über weite Strecken seiner Kolonialgeschichte unter spanischer Verwaltung, unterbrochen von einer britischen Phase im 18. Jahrhundert. St. Augustine zeugt als älteste Gründung besonders deutlich von dieser Zeit.",
    tip: "Das Castillo de San Marcos in St. Augustine ist die älteste erhaltene Steinfestung auf dem Gebiet der heutigen USA.", tags: ["Geschichte"] },
  { id: "t17", cat: "planning", region: "Südflorida", name: "Seminole-Geschichte", icon: "", lat: null, lon: null,
    desc: "Die Seminolen, ein aus verschiedenen indigenen Gruppen hervorgegangenes Volk, zogen sich im 19. Jahrhundert in die schwer zugänglichen Everglades zurück und gehören zu den wenigen indigenen Nationen der USA, die nie eine offizielle Kapitulation unterzeichneten.",
    tip: "Mehrere von der Seminolen-Nation selbst betriebene Kultureinrichtungen in Südflorida vermitteln die Geschichte aus erster Hand.", tags: ["Geschichte", "Kultur"] },
  { id: "t18", cat: "planning", region: "Zentralflorida", name: "Zitrusindustrie-Geschichte", icon: "", lat: null, lon: null,
    desc: "Der großflächige Anbau von Orangen und Grapefruits prägt Zentralflorida seit dem späten 19. Jahrhundert und war jahrzehntelang einer der wichtigsten Wirtschaftszweige des Bundesstaates, auch wenn Frost-Ereignisse die Anbaugebiete im Lauf der Zeit nach Süden verschoben haben.",
    tip: "Das Motiv der Orange taucht bis heute auf Nummernschildern und im Bundesstaats-Branding auf.", tags: ["Geschichte", "Wirtschaft"] },
  { id: "t19", cat: "planning", region: "Zentralflorida", name: "Raumfahrt-Geschichte der Space Coast", icon: "", lat: null, lon: null,
    desc: "Die Küstenregion um Cape Canaveral wurde ab den 1950er-Jahren zum Zentrum des US-Raumfahrtprogramms und war Ausgangspunkt sämtlicher bemannter Mondmissionen der Apollo-Ära.",
    tip: "Startzeiten aktueller Raketenstarts werden vorab veröffentlicht – bei gutem Wetter oft auch von Stränden der Umgebung aus sichtbar.", tags: ["Geschichte", "Raumfahrt"] },

  { id: "w1", cat: "wildlife", region: "Allgemein", name: "Amerikanischer Alligator", icon: "", lat: null, lon: null,
    desc: "Das namensgebende Reptil der Feuchtgebiete Floridas ist in nahezu allen Süßwasserlebensräumen des Bundesstaates verbreitet, von Sümpfen bis zu Vorstadt-Kanälen. Nach starkem Rückgang im 20. Jahrhundert gilt der Bestand heute als erholt.",
    tip: "Alligatoren sind von Natur aus scheu, reagieren aber aggressiv, wenn sie sich bedrängt fühlen oder gefüttert wurden – Fütterung ist deshalb verboten.", tags: ["Reptil", "Everglades"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w2", cat: "wildlife", region: "Allgemein", name: "Florida-Seekuh (Manatee)", icon: "", lat: null, lon: null,
    desc: "Die sanftmütige Rundschwanzseekuh lebt in Küstengewässern, Flüssen und warmen Quellen und zieht sich im Winter in wärmere Gewässer wie bei Crystal River zurück, um der Kälte zu entgehen.",
    tip: "Bootsverkehr ist eine der Hauptgefahren für Manatees – in ausgewiesenen Schutzzonen gelten daher niedrige Geschwindigkeitsbegrenzungen.", tags: ["Meeressäuger"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w3", cat: "wildlife", region: "Südflorida", name: "Rosalöffler (Roseate Spoonbill)", icon: "", lat: null, lon: null,
    desc: "Der auffällig pinke, langschnäblige Watvogel wird in Florida oft mit Flamingos verwechselt – echte wildlebende Flamingos sind hier dagegen selten. Rosalöffler sind vor allem in den Everglades und an der Golfküste zu beobachten.",
    tip: "Die pinke Färbung stammt, ähnlich wie bei Flamingos, aus der Nahrung – vor allem aus Krebstieren.", tags: ["Vogel", "Everglades"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w4", cat: "wildlife", region: "Allgemein", name: "Brauner Pelikan", icon: "", lat: null, lon: null,
    desc: "Der Braune Pelikan ist an nahezu jedem Küstenabschnitt Floridas zu beobachten, oft im charakteristischen Sturzflug bei der Jagd nach Fischen direkt vor der Küste.",
    tip: "Anlegestellen und Fischereihäfen sind zuverlässige Beobachtungsorte, da Pelikane hier häufig auf Fischabfälle warten.", tags: ["Vogel", "Küste"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w5", cat: "wildlife", region: "Allgemein", name: "Großer Tümmler (Delfin)", icon: "", lat: null, lon: null,
    desc: "Große Tümmler sind in den Küstengewässern Floridas ganzjährig heimisch und werden regelmäßig von Stränden, Piers und Bootstouren aus gesichtet.",
    tip: "Bootstouren mit Fokus auf Delfin-Beobachtung gibt es an praktisch jeder größeren Küstenstadt.", tags: ["Meeressäuger", "Küste"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w6", cat: "wildlife", region: "Florida Keys", name: "Loggerhead-Meeresschildkröte", icon: "", lat: null, lon: null,
    desc: "Floridas Strände zählen zu den wichtigsten Nistgebieten der bedrohten Loggerhead-Meeresschildkröte weltweit. Von Mai bis Oktober legen die Weibchen ihre Eier in Sandnestern oberhalb der Flutlinie ab.",
    tip: "Während der Nistsaison an vielen Stränden nachts Taschenlampen und helles Licht vermeiden, da es schlüpfende Jungtiere desorientiert.", tags: ["Meeresschildkröte", "Naturschutz"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w7", cat: "wildlife", region: "Südflorida", name: "Florida-Panther", icon: "", lat: null, lon: null,
    desc: "Der Florida-Panther, eine Unterart des Pumas, gilt als eine der am stärksten gefährdeten Großkatzen Nordamerikas. Sein verbliebenes Verbreitungsgebiet konzentriert sich auf Wälder und Sümpfe rund um Big Cypress.",
    tip: "Sichtungen in freier Wildbahn sind selten – am ehesten dokumentieren Wildkameras in Schutzgebieten die scheuen Tiere.", tags: ["Raubkatze", "Naturschutz"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w8", cat: "wildlife", region: "Allgemein", name: "Sabalpalme", icon: "", lat: null, lon: null,
    desc: "Die Sabalpalme ist der offizielle Staatsbaum Floridas und prägt mit ihrer charakteristischen Silhouette das Landschaftsbild von der Küste bis ins Landesinnere.",
    tip: "Junge Blattherzen der Sabalpalme galten früher als Delikatesse ('Hearts of Palm') – heute meist aus nachhaltigerem Anbau statt Wildbestand.", tags: ["Pflanze", "Symbol"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w9", cat: "wildlife", region: "Südflorida", name: "Mangroven", icon: "", lat: null, lon: null,
    desc: "Mangrovenwälder säumen weite Teile der Küste Süd- und Südwestfloridas und bilden als Wurzelgeflecht im Brackwasser einen wichtigen Lebensraum für Jungfische und Vögel sowie einen natürlichen Küstenschutz.",
    tip: "Kajak-Touren durch Mangrovenkanäle zeigen dieses Ökosystem oft eindrucksvoller als vom Ufer aus.", tags: ["Pflanze", "Ökosystem"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w10", cat: "wildlife", region: "Allgemein", name: "Anhinga (Schlangenhalsvogel)", icon: "", lat: null, lon: null,
    desc: "Der Schlangenhalsvogel taucht auf der Jagd nach Fischen vollständig unter und durchbohrt seine Beute mit dem spitzen Schnabel. Da sein Gefieder nicht wasserabweisend ist, sitzt er danach oft mit ausgebreiteten Flügeln zum Trocknen da.",
    tip: "Dieses charakteristische Flügel-Trocknen macht ihn oft leichter zu erkennen als beim Schwimmen selbst.", tags: ["Vogel", "Everglades"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w11", cat: "wildlife", region: "Allgemein", name: "Gopher-Schildkröte", icon: "", lat: null, lon: null,
    desc: "Diese Landschildkröte gräbt tiefe, weit verzweigte Erdhöhlen, die auch vielen anderen Arten (u. a. Schlangen und Fröschen) als Unterschlupf dienen — daher gilt sie als „Schlüsselart” der Sandkiefernwälder.",
    tip: "Ihre Erdhöhlen sind an sandigen Hügeln oft an dem halbmondförmigen Aushub vor dem Eingang erkennbar.", tags: ["Reptil", "Naturschutz"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w12", cat: "wildlife", region: "Allgemein", name: "Florida-Buschhäher", icon: "", lat: null, lon: null,
    desc: "Einzige Vogelart, die ausschließlich in Florida vorkommt (endemisch) und nirgendwo sonst auf der Welt brütet. Lebt in Familienverbänden in den seltener werdenden Sandkiefern-Buschlandschaften.",
    tip: "Er gilt als vergleichsweise zutraulich und neugierig gegenüber Menschen — Fütterung ist dennoch nicht erlaubt.", tags: ["Vogel", "Endemisch"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },
  { id: "w13", cat: "wildlife", region: "Allgemein", name: "Rosalöffler", icon: "", lat: null, lon: null,
    desc: "Auffällig pink gefärbter Watvogel, der oft mit Flamingos verwechselt wird. Die Färbung stammt wie bei Flamingos aus der Nahrung (u. a. Krebstiere) und variiert je nach Ernährung in der Intensität.",
    tip: "Am ehesten in flachen Lagunen und Mangrovengebieten der Everglades und der Golfküste zu beobachten.", tags: ["Vogel", "Everglades"],
    bestTime: "Je nach Art unterschiedlich, siehe Beschreibung", costHint: "Kostenlos in freier Wildbahn, günstig bis mittel bei geführten Touren" },

  { id: "h1", cat: "history", region: "Nordflorida", name: "Castillo de San Marcos", icon: "", lat: 29.8977, lon: -81.3122,
    desc: "Älteste noch erhaltene Steinfestung auf dem Festland der USA, im späten 17. Jahrhundert von Spanien zum Schutz von St. Augustine errichtet. Die Mauern bestehen aus Coquina, einem lokalen Muschelkalkstein.",
    tip: "Bei einigen Nachmittagsführungen wird historische Kanonenbedienung demonstriert — Termine vorher online prüfen.", tags: ["Festung", "Spanische Kolonialzeit"],
    bestTime: "Ganzjährig gut besuchbar, Vormittage oft ruhiger", costHint: "Günstig" },
  { id: "h2", cat: "history", region: "Nordflorida", name: "Fort Matanzas National Monument", icon: "", lat: 29.7203, lon: -81.2383,
    desc: "Kleiner spanischer Wachturm aus dem 18. Jahrhundert an der Mündung des Matanzas River, ursprünglich zur Überwachung eines südlichen Zugangs nach St. Augustine errichtet.",
    tip: "Die kostenlose Fähre zur Festungsinsel fährt nur zu festen Zeiten — Ankunft rechtzeitig einplanen.", tags: ["Festung", "Spanische Kolonialzeit"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Kostenlos" },
  { id: "h3", cat: "history", region: "Florida Keys", name: "Fort Zachary Taylor Historic State Park", icon: "", lat: 24.5455, lon: -81.8090,
    desc: "Festung aus der Zeit des Amerikanischen Bürgerkriegs in Key West, die während des Krieges unter Unions-Kontrolle blieb. Das Gelände umfasst zugleich einen ruhigen Strandabschnitt.",
    tip: "Der vorgelagerte Strand gilt als einer der besten Schnorchel-Spots direkt in Key West.", tags: ["Festung", "Bürgerkrieg", "Strand"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig" },
  { id: "h4", cat: "history", region: "Zentralflorida", name: "Bok Tower Gardens", icon: "", lat: 27.9382, lon: -81.6009,
    desc: "Historische Gartenanlage aus den 1920er-Jahren rund um einen 60 Meter hohen neogotischen Glockenturm (Carillon) auf einer der höchsten natürlichen Erhebungen Floridas.",
    tip: "Die Carillon-Konzerte finden mehrmals täglich statt — Zeiten sind am Eingang ausgehängt.", tags: ["Garten", "Architektur", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar, Frühling wegen der Blüte besonders beliebt", costHint: "Mittel" },
  { id: "h5", cat: "history", region: "Südflorida", name: "Flagler Museum (Whitehall)", icon: "", lat: 26.7080, lon: -80.0377,
    desc: "Ehemaliges Privathaus des Eisenbahn- und Hotelunternehmers Henry Flagler in Palm Beach, erbaut 1902 im Stil der Gilded-Age-Ära. Gilt als eines der aufwendigsten historischen Herrenhäuser Floridas.",
    tip: "Im hauseigenen Eisenbahnwaggon-Pavillon steht Flaglers original erhaltener Privatwaggon.", tags: ["Museum", "Architektur", "Gilded Age"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "h6", cat: "history", region: "Zentralflorida", name: "Crystal River Archaeological State Park", icon: "", lat: 28.9046, lon: -82.5864,
    desc: "Eine der am längsten durchgehend genutzten präkolumbischen Ureinwohner-Stätten Floridas, mit mehreren erhaltenen Hügelbauten (Mounds), die über etwa 1.600 Jahre errichtet wurden.",
    tip: "Ein kurzer Rundweg führt an allen wichtigen Hügeln vorbei, ein kleines Besucherzentrum ordnet die Fundstücke ein.", tags: ["Ureinwohner", "Archäologie", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Günstig" },

  { id: "a1", cat: "art", region: "Zentralflorida", name: "The Ringling", icon: "", lat: 27.3776, lon: -82.5541,
    desc: "Umfangreicher Museumskomplex in Sarasota, den Zirkusunternehmer John Ringling in den 1920er-Jahren gründete: europäische Gemäldesammlung, ein Zirkusmuseum sowie sein historisches Herrenhaus Ca' d'Zan direkt an der Bucht.",
    tip: "Für alle drei Bereiche (Kunstmuseum, Zirkusmuseum, Herrenhaus) sollte man einen halben bis ganzen Tag einplanen.", tags: ["Museum", "Architektur"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "a2", cat: "art", region: "Zentralflorida", name: "Dalí Museum", icon: "", lat: 27.7661, lon: -82.6353,
    desc: "Museum in St. Petersburg mit einer der weltweit größten Sammlungen von Werken Salvador Dalís außerhalb Spaniens, in einem markanten Gebäude mit geodätischer Glaskuppel direkt an der Bucht.",
    tip: "Der Garten mit der begehbaren Spiegel-Installation ist auch ohne Museumsticket zugänglich.", tags: ["Museum", "Moderne Kunst"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "a3", cat: "art", region: "Südflorida", name: "Norton Museum of Art", icon: "", lat: 26.7168, lon: -80.0526,
    desc: "Eines der größten Kunstmuseen Floridas in West Palm Beach, mit Sammlungsschwerpunkten auf amerikanischer, europäischer, chinesischer und zeitgenössischer Kunst sowie einem ruhigen Skulpturengarten.",
    tip: "Der Skulpturengarten eignet sich auch für eine kurze Pause zwischendurch, nicht nur für den vollen Museumsbesuch.", tags: ["Museum", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "a4", cat: "art", region: "Südflorida", name: "Pérez Art Museum Miami", icon: "", lat: 25.7857, lon: -80.1867,
    desc: "Zeitgenössisches Kunstmuseum direkt an der Bucht von Miami, bekannt für sein von hängenden Gärten umgebenes Gebäude sowie wechselnde internationale Ausstellungen.",
    tip: "Die überdachte Terrasse mit Bucht-Blick lohnt einen Besuch auch unabhängig von den Ausstellungen.", tags: ["Museum", "Moderne Kunst", "Aussicht"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "a5", cat: "art", region: "Südflorida", name: "Morikami Museum and Japanese Gardens", icon: "", lat: 26.4188, lon: -80.1495,
    desc: "Museum und weitläufige japanische Gartenanlage bei Delray Beach, entstanden aus einer historischen japanischen Landwirtschafts-Kolonie in Florida. Sechs unterschiedlich gestaltete Gartenbereiche greifen verschiedene Epochen japanischer Gartenkunst auf.",
    tip: "Ein Spaziergang durch alle sechs Gartenbereiche dauert erfahrungsgemäß ein bis zwei Stunden.", tags: ["Garten", "Museum", "Ruhig"],
    bestTime: "Ganzjährig gut besuchbar", costHint: "Mittel" },
  { id: "a6", cat: "art", region: "Südflorida", name: "Wynwood Walls", icon: "", lat: 25.8010, lon: -80.1990,
    desc: "Im früheren Industrieviertel Wynwood in Miami gelegene, kuratierte Freiluft-Galerie mit großflächigen Wandgemälden international bekannter Street-Art-Künstler — heute Ausgangspunkt eines ganzen Viertels voller Murals.",
    tip: "Rund um die eigentlichen Wynwood Walls lohnt ein Spaziergang durch die Nebenstraßen, da dort viele weitere Wandbilder frei zugänglich sind.", tags: ["Street Art", "Viertel"],
    bestTime: "Ganzjährig gut besuchbar, spätnachmittags angenehmes Licht für Fotos", costHint: "Günstig bis mittel" },

  { id: "o1", cat: "adventure", region: "Südflorida", name: "Airboat-Tour durch die Everglades", icon: "", lat: null, lon: null,
    desc: "Flachbodige, propellergetriebene Boote ermöglichen die Fahrt durch die seichten Marschgebiete der Everglades, wo Alligatoren und Watvögel aus nächster Nähe zu beobachten sind.",
    tip: "Anbieter mit kleineren Booten und Gruppengrößen bieten in der Regel ein ruhigeres, persönlicheres Erlebnis.", tags: ["Everglades", "Tiere", "Boot"],
    bestTime: "Ganzjährig möglich, kühlere Morgenstunden oft angenehmer", costHint: "Mittel bis gehoben" },
  { id: "o2", cat: "adventure", region: "Allgemein", name: "Kajak-Touren durch Mangrovenkanäle", icon: "", lat: null, lon: null,
    desc: "Zahlreiche Küstenabschnitte Floridas bieten geführte oder eigenständige Kajaktouren durch enge, von Mangroven gesäumte Wasserwege — ruhig, naturnah und häufig mit Sichtungen von Watvögeln oder Delfinen.",
    tip: "Ausrüster verleihen Kajaks meist tage- oder stundenweise, eine vorherige Reservierung ist in der Hauptsaison ratsam.", tags: ["Wasser", "Natur", "Aktiv"],
    bestTime: "Ganzjährig möglich, Vormittage meist weniger windig", costHint: "Günstig bis mittel" },
  { id: "o3", cat: "adventure", region: "Allgemein", name: "Hochseeangeln (Deep-Sea Fishing)", icon: "", lat: null, lon: null,
    desc: "Ganztägige oder halbtägige Bootstouren auf offener See, meist mit Zielarten wie Grouper, Snapper oder Mahi-Mahi. Charterboote stellen üblicherweise Ausrüstung und Angelscheine für Gäste bereit.",
    tip: "Halbtagestouren sind für Einsteiger meist ausreichend und deutlich günstiger als Ganztagestouren.", tags: ["Wasser", "Angeln"],
    bestTime: "Ganzjährig möglich, je nach Zielfischart saisonal unterschiedlich ergiebig", costHint: "Mittel bis gehoben" },
  { id: "o4", cat: "adventure", region: "Zentralflorida", name: "Zipline- und Baumwipfelpfad-Touren", icon: "", lat: null, lon: null,
    desc: "Mehrere Naturparks und private Anbieter betreiben Seilbahn- und Hängebrücken-Parcours durch die Baumkronen, teils kombiniert mit Kletterelementen für unterschiedliche Schwierigkeitsgrade.",
    tip: "Geschlossenes Schuhwerk ist bei praktisch allen Anbietern Pflicht.", tags: ["Aktiv", "Natur", "Familien"],
    bestTime: "Ganzjährig möglich, an heißen Nachmittagen im Schatten der Bäume angenehmer", costHint: "Mittel" },
  { id: "o5", cat: "adventure", region: "Florida Keys", name: "Schnorcheln und Tauchen am Korallenriff", icon: "", lat: null, lon: null,
    desc: "Das einzige lebende Korallenriff-System der USA verläuft entlang der Florida Keys. Zahlreiche Ausrüster bieten Boots-Ausfahrten sowohl für Schnorchler als auch für zertifizierte Taucher an.",
    tip: "Riffverträglicher (mineralischer statt chemischer) Sonnenschutz wird von vielen Anbietern inzwischen vorausgesetzt.", tags: ["Wasser", "Riff", "Tiere"],
    bestTime: "Ganzjährig möglich, Sommer bietet meist die beste Sichtweite", costHint: "Mittel bis gehoben" },
  { id: "o6", cat: "adventure", region: "Zentralflorida", name: "Heißluftballonfahrt", icon: "", lat: null, lon: null,
    desc: "Frühmorgendliche Ballonfahrten über den Seen- und Wiesenlandschaften Zentralfloridas, meist mit Start kurz nach Sonnenaufgang bei ruhigsten Windverhältnissen.",
    tip: "Aus Wettergründen werden Termine häufig kurzfristig verschoben — Flexibilität beim Reisedatum hilft.", tags: ["Aussicht", "Sonnenaufgang"],
    bestTime: "Ganzjährig möglich, früher Morgen mit ruhigster Witterung", costHint: "Gehoben" },
  { id: "o7", cat: "adventure", region: "Allgemein", name: "Stand-Up-Paddling", icon: "", lat: null, lon: null,
    desc: "Ruhige Buchten und Flussmündungen an der Golfküste eignen sich gut zum Stand-Up-Paddling, auch für Einsteiger. Manche Anbieter bieten geführte Touren mit durchsichtigen Boards zur Fischbeobachtung an.",
    tip: "Frühe Morgenstunden bieten meist spiegelglattes Wasser und weniger Bootsverkehr.", tags: ["Wasser", "Aktiv"],
    bestTime: "Ganzjährig möglich, morgens meist ruhigeres Wasser", costHint: "Günstig bis mittel" },
  { id: "o8", cat: "adventure", region: "Allgemein", name: "Wandern in State Parks", icon: "", lat: null, lon: null,
    desc: "Floridas State Parks unterhalten ein dichtes Netz beschilderter Wanderwege durch Sumpfwälder, Sandkiefernlandschaften und entlang von Quellen — von kurzen Rundwegen bis zu mehrstündigen Touren.",
    tip: "Insektenschutz und ausreichend Wasser gehören auch bei kurzen Wanderungen ins Gepäck.", tags: ["Natur", "Aktiv", "Kostenlos bis günstig"],
    bestTime: "November bis April angenehmer, Sommer schwül und moskitoreich", costHint: "Günstig (Parkgebühr)" },
];

const WEATHER_CITIES = [
  { name: "Miami", lat: 25.7617, lon: -80.1918 },
  { name: "Orlando", lat: 28.5383, lon: -81.3792 },
  { name: "Tampa", lat: 27.9506, lon: -82.4572 },
  { name: "Key West", lat: 24.5551, lon: -81.7800 },
  { name: "Jacksonville", lat: 30.3322, lon: -81.6557 },
  { name: "Pensacola", lat: 30.4213, lon: -87.2169 },
  { name: "Naples", lat: 26.1420, lon: -81.7948 },
];

const EDITORIAL_TIPS = [
  { cat: "Planung & Buchung", text: "Reserviere beliebte Restaurants und Themenpark-Attraktionen möglichst schon vor der Reise online." },
  { cat: "Planung & Buchung", text: "Die Nebensaison im September und Oktober bietet oft die günstigsten Preise, fällt aber in die aktive Hurrikansaison." },
  { cat: "Planung & Buchung", text: "Orlando hat zwei Flughäfen (MCO und Sanford/SFB) — bei Billigfliegern lohnt ein Blick, welcher gemeint ist, da beide unterschiedlich weit von den Parks liegen." },
  { cat: "Planung & Buchung", text: "Weihnachten/Neujahr und die Osterferien (Spring Break, meist März) sind Spitzenzeiten mit den höchsten Preisen und vollsten Parks." },
  { cat: "Wetter & Klima", text: "Sommernachmittage bringen fast täglich kurze, kräftige Gewitter – Vormittage eignen sich oft besser für Outdoor-Programm." },
  { cat: "Wetter & Klima", text: "Der Golf von Mexiko ist an der Westküste meist ruhiger und wärmer als der Atlantik an der Ostküste." },
  { cat: "Wetter & Klima", text: "Sonnenbrand entsteht in Florida auch bei bewölktem Himmel schnell – Sonnenschutz gehört auch an trüben Tagen aufgetragen." },
  { cat: "Wetter & Klima", text: "Die Hurrikansaison läuft offiziell von Juni bis November – Warnungen der US-Wetterbehörde NOAA/des National Hurricane Center sollten immer ernst genommen werden." },
  { cat: "Wetter & Klima", text: "Die Luftfeuchtigkeit ist im Sommer oft sehr hoch – die gefühlte Temperatur liegt spürbar über der angezeigten." },
  { cat: "Sicherheit & Natur", text: "Alligatoren sind in Florida allgegenwärtig, auch in Vorstadt-Kanälen – Warnschilder ernst nehmen und Abstand halten." },
  { cat: "Sicherheit & Natur", text: "In Naturschutzgebieten nie Wildtiere füttern – das ist in der Regel verboten und für die Tiere schädlich." },
  { cat: "Sicherheit & Natur", text: "Quallen können auch außerhalb der Hauptsaison an Stränden auftreten – Warnflaggen-Systeme an bewachten Stränden beachten." },
  { cat: "Sicherheit & Natur", text: "Moskitorepellent mit DEET oder Picaridin ist in feuchten, bewaldeten Gebieten besonders in den Abendstunden empfehlenswert." },
  { cat: "Sicherheit & Natur", text: "An Atlantikstränden können gefährliche Strömungen (Rip Currents) auftreten – bei roter Flagge nicht ins Wasser gehen." },
  { cat: "Sicherheit & Natur", text: "Florida zählt zu den blitzreichsten Regionen der USA – bei aufziehendem Gewitter zügig Innenräume oder ein Fahrzeug aufsuchen." },
  { cat: "Geld & Kosten", text: "Viele State Parks verlangen eine Tages- oder Fahrzeuggebühr vor Ort in bar oder Karte – etwas Kleingeld einplanen." },
  { cat: "Geld & Kosten", text: "Parkgebühren in Innenstädten wie Miami oder Key West können sich über den Tag deutlich summieren – Parkhäuser vorab vergleichen." },
  { cat: "Geld & Kosten", text: "Mietwagen-Tankstellen direkt am Flughafen sind oft teurer als Stationen wenige Kilometer entfernt – vor der Rückgabe außerhalb tanken." },
  { cat: "Geld & Kosten", text: "Trinkgeld wird in der Regel bar oder als separater Betrag auf der Kartenzahlung hinzugefügt, nicht im Preis inbegriffen." },
  { cat: "Geld & Kosten", text: "Rabattierte Mehrtages-Eintrittskarten für Themenparks lohnen sich oft schon ab zwei Besuchstagen im selben Park." },
  { cat: "Geld & Kosten", text: "Wechselgeld in kleinen Scheinen ist praktisch für Trinkgelder, Parkuhren und kleinere Marktstände." },
  { cat: "Geld & Kosten", text: "Viele Hotels berechnen zusätzlich zum Zimmerpreis eine tägliche „Resort Fee” – oft erst im Kleingedruckten der Buchung sichtbar." },
  { cat: "Geld & Kosten", text: "Bei Themenparks kommt die Parkplatzgebühr meist separat zum Eintrittspreis hinzu und kann sich über mehrere Besuchstage summieren." },
  { cat: "Verkehr & Mietwagen", text: "Öffentlicher Nahverkehr ist außerhalb der großen Innenstädte oft lückenhaft – für Tagesausflüge ist ein Mietwagen meist praktischer." },
  { cat: "Verkehr & Mietwagen", text: "Autobahn-Mautgebühren werden bei Mietwagen oft automatisch per Kennzeichenerfassung abgerechnet und später der Mietwagenfirma in Rechnung gestellt – das kann teurer sein als ein Mautpass." },
  { cat: "Verkehr & Mietwagen", text: "Bei Fahrten über den Overseas Highway durch die Keys reicht meist deutlich mehr Zeit ein als die reine Fahrstrecke vermuten lässt – zahlreiche Brücken und Tempolimits verlangsamen die Fahrt." },
  { cat: "Verkehr & Mietwagen", text: "In den USA herrscht Rechtsverkehr, Rechtsabbiegen bei Rot ist meist erlaubt, sofern nicht ausdrücklich durch Schilder untersagt." },
  { cat: "Verkehr & Mietwagen", text: "Tempolimits werden konsequent überwacht, in Baustellenbereichen gelten oft verdoppelte Strafen." },
  { cat: "Praktisches vor Ort", text: "Klimaanlagen sind in Innenräumen häufig sehr stark eingestellt – eine leichte Jacke lohnt sich auch im Sommer." },
  { cat: "Praktisches vor Ort", text: "Supermärkte wie Publix bieten oft günstige, fertig belegte Sandwiches – praktisch für Strandtage." },
  { cat: "Praktisches vor Ort", text: "In vielen Restaurants wird Eiswasser automatisch und kostenlos serviert, wenn nicht anders gewünscht." },
  { cat: "Praktisches vor Ort", text: "Strandzugänge sind nicht überall öffentlich – manche Abschnitte gehören zu Hotels oder privaten Anliegern." },
  { cat: "Praktisches vor Ort", text: "Strandparkplätze an beliebten Orten füllen sich an Wochenenden oft schon vormittags – früh anreisen oder Alternativen einplanen." },
  { cat: "Praktisches vor Ort", text: "Manche State Parks und Strände schließen ihre Zufahrt vorübergehend, sobald die Parkplätze voll sind – Ausweichziele in der Nähe kennen hilft." },
  { cat: "Praktisches vor Ort", text: "Fast alle Themenparks erlauben das Mitbringen eigener Getränke und Snacks in Taschen – ein Blick in die aktuellen Regeln vor dem Besuch lohnt sich." },
  { cat: "Praktisches vor Ort", text: "Steckdosen folgen dem US-Standard (Typ A/B, 110 Volt) – für europäische Geräte wird meist ein Adapter, teils auch ein Spannungswandler benötigt." },
  { cat: "Praktisches vor Ort", text: "Leitungswasser ist in Florida überall unbedenklich trinkbar." },
  { cat: "Planung & Buchung", text: "Restaurant-Reservierungsportale wie OpenTable sind in vielen Städten Floridas verbreitet und oft die zuverlässigste Art, einen Tisch zu bekommen." },
  { cat: "Planung & Buchung", text: "Manche Themenpark-Attraktionen und beliebte Restaurants lassen sich Monate im Voraus reservieren — bei sehr gefragten Terminen lohnt frühzeitiges Buchen." },
  { cat: "Wetter & Klima", text: "Die Wassertemperatur an der Golfküste bleibt auch im Winter meist milder als am Atlantik, da der Golf von Mexiko wärmer ist." },
  { cat: "Wetter & Klima", text: "Nebel kommt in Florida selten, aber gerade in den frühen Morgenstunden über Sümpfen und Seen gelegentlich vor — vorsichtiges Fahren ist dann ratsam." },
  { cat: "Sicherheit & Natur", text: "Feuerameisen (Fire Ants) bilden charakteristische kleine Erdhügel und können schmerzhaft stechen — auf Grasflächen auf solche Hügel achten." },
  { cat: "Sicherheit & Natur", text: "Klapperschlangen sind in ländlichen und bewaldeten Gebieten heimisch, aber meist scheu — auf markierten Wegen bleiben senkt das Risiko einer Begegnung deutlich." },
  { cat: "Geld & Kosten", text: "Kreditkarten werden praktisch überall akzeptiert, auch für sehr kleine Beträge — Bargeld wird seltener benötigt als in Deutschland." },
  { cat: "Geld & Kosten", text: "Manche Anbieter erheben bei Kreditkartenzahlung eine kleine zusätzliche Gebühr (Surcharge) — ein Blick auf den Kassenbon lohnt sich." },
  { cat: "Geld & Kosten", text: "Museums- und Aquarien-Jahreskarten rechnen sich oft schon ab zwei bis drei Besuchen während eines längeren Aufenthalts." },
  { cat: "Verkehr & Mietwagen", text: "Schulbusse mit ausgeklapptem Stoppschild dürfen in beide Fahrtrichtungen nicht überholt werden — das gilt auch auf mehrspurigen Straßen." },
  { cat: "Verkehr & Mietwagen", text: "Tankstellen verlangen bei Kartenzahlung an der Zapfsäule teils eine amerikanische Postleitzahl — im Zweifel drinnen an der Kasse bezahlen." },
  { cat: "Praktisches vor Ort", text: "Die Nebensaison-Monate bringen in Innenräumen oft besonders kalt eingestellte Klimaanlagen, da diese ganzjährig auf Spitzenlast ausgelegt sind." },
  { cat: "Praktisches vor Ort", text: "Öffentliches WLAN ist in Einkaufszentren, Cafés und den meisten Hotels verbreitet verfügbar, in ländlicheren Gegenden aber lückenhafter." },
];

const PHRASEBOOK = [
  { cat: "Grundlagen", en: "Hello / Hi", de: "Hallo" },
  { cat: "Grundlagen", en: "Thank you (very much)", de: "Danke (vielen Dank)" },
  { cat: "Grundlagen", en: "Please", de: "Bitte" },
  { cat: "Grundlagen", en: "Excuse me / Sorry", de: "Entschuldigung" },
  { cat: "Grundlagen", en: "Do you speak German?", de: "Sprechen Sie Deutsch?" },
  { cat: "Grundlagen", en: "I don't understand.", de: "Ich verstehe nicht." },
  { cat: "Grundlagen", en: "Could you repeat that, please?", de: "Könnten Sie das bitte wiederholen?" },
  { cat: "Grundlagen", en: "Have a nice day!", de: "Schönen Tag noch!" },

  { cat: "Restaurant", en: "Table for two, please.", de: "Einen Tisch für zwei, bitte." },
  { cat: "Restaurant", en: "Could I get the check, please?", de: "Könnte ich bitte die Rechnung bekommen?" },
  { cat: "Restaurant", en: "Is tap water free?", de: "Ist Leitungswasser kostenlos?" },
  { cat: "Restaurant", en: "I'm allergic to…", de: "Ich bin allergisch gegen…" },
  { cat: "Restaurant", en: "Could we split the check?", de: "Können wir getrennt zahlen?" },
  { cat: "Restaurant", en: "Is this dish spicy?", de: "Ist dieses Gericht scharf?" },
  { cat: "Restaurant", en: "No ice, please.", de: "Ohne Eis, bitte." },

  { cat: "Unterwegs", en: "Where is the nearest restroom?", de: "Wo ist die nächste Toilette?" },
  { cat: "Unterwegs", en: "Where is the nearest gas station?", de: "Wo ist die nächste Tankstelle?" },
  { cat: "Unterwegs", en: "Fill it up, please.", de: "Bitte volltanken." },
  { cat: "Unterwegs", en: "Is this seat taken?", de: "Ist dieser Platz besetzt?" },
  { cat: "Unterwegs", en: "How do I get to…?", de: "Wie komme ich zu…?" },
  { cat: "Unterwegs", en: "Is it within walking distance?", de: "Ist das fußläufig erreichbar?" },
  { cat: "Unterwegs", en: "Does this include parking?", de: "Ist Parken inbegriffen?" },

  { cat: "Shopping", en: "How much does this cost?", de: "Wie viel kostet das?" },
  { cat: "Shopping", en: "Do you accept credit cards?", de: "Akzeptieren Sie Kreditkarten?" },
  { cat: "Shopping", en: "Can I try this on?", de: "Kann ich das anprobieren?" },
  { cat: "Shopping", en: "Is this on sale?", de: "Ist das reduziert?" },
  { cat: "Shopping", en: "Could I get a receipt, please?", de: "Könnte ich bitte eine Quittung bekommen?" },

  { cat: "Notfall", en: "I need a doctor.", de: "Ich brauche einen Arzt." },
  { cat: "Notfall", en: "Call 911, please!", de: "Rufen Sie bitte die 911!" },
  { cat: "Notfall", en: "I've lost my passport.", de: "Ich habe meinen Reisepass verloren." },
  { cat: "Notfall", en: "I need help, please.", de: "Ich brauche bitte Hilfe." },
  { cat: "Notfall", en: "Where is the nearest hospital?", de: "Wo ist das nächste Krankenhaus?" },
  { cat: "Notfall", en: "My wallet was stolen.", de: "Mein Portemonnaie wurde gestohlen." },
];

/* Einträge zeigen statt Emojis das eigene, selbst gezeichnete Symbol ihrer Kategorie */
(function () {
  const byCat = {};
  CATEGORIES.forEach((c) => { byCat[c.id] = c.icon; });
  ENTRIES.forEach((e) => {
    const src = byCat[e.cat];
    e.icon = src ? `<img class="cat-ic" src="${src}" alt="">` : "";
  });
})();
